version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend
    networks:
      - private

  frontend:
    build: ./frontend
    container_name: frontend
    networks:
      - private

  proxy:
    build: ./proxy/http
    container_name: proxy
    ports:
      - "80:80"
      - "443:443"
    networks:
      - private
    depends_on:
      - backend
    restart: always

networks:
  private:
    driver: bridge



