version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend
    networks:
      - default
  
  frontend:
    build: ./frontend
    container_name: frontend
    networks:
      - default
  proxy:
    build: ./proxy/http
    container_name: proxy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend
    networks:
      - default

networks:
  default:
    driver: bridge


